""" You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""


def findTheDifference(s, t) :
        dic = {}
        if s == "":
            return t
        for i in s:
            if i not in dic:
                dic[i] = 1
            else:
                dic[i] += 1
        for j in t:
            if j in dic and dic[j] != 0:
                dic[j] -= 1
            elif j not in dic:
                return j
            else:
                return j
print(findTheDifference("abcd", "abcde"))